import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#fcf9f8",
        foreground: "#1b1c1c",
        primary: "#a5161d",
        "on-primary": "#ffffff",
        "primary-container": "#c83232",
        "on-primary-container": "#ffe9e6",
        "primary-fixed": "#ffdad6",
        "primary-fixed-dim": "#ffb3ad",
        "on-primary-fixed": "#410003",
        "on-primary-fixed-variant": "#920212",
        secondary: "#0060ac",
        "on-secondary": "#ffffff",
        "secondary-container": "#68abff",
        "on-secondary-container": "#003e73",
        "secondary-fixed": "#d4e3ff",
        "secondary-fixed-dim": "#a4c9ff",
        "on-secondary-fixed": "#001c39",
        "on-secondary-fixed-variant": "#004883",
        tertiary: "#006111",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#007d19",
        "on-tertiary-container": "#b8ffad",
        "tertiary-fixed": "#84fd7d",
        "tertiary-fixed-dim": "#67df64",
        "on-tertiary-fixed": "#002202",
        "on-tertiary-fixed-variant": "#00530d",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        surface: "#fcf9f8",
        "on-surface": "#1b1c1c",
        "surface-variant": "#e4e2e1",
        "on-surface-variant": "#5a403e",
        "surface-bright": "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0eded",
        "surface-container-high": "#eae7e7",
        "surface-container-highest": "#e4e2e1",
        "inverse-surface": "#303030",
        "inverse-on-surface": "#f3f0f0",
        "inverse-primary": "#ffb3ad",
        "surface-tint": "#b52427",
        outline: "#8e706d",
        "outline-variant": "#e2bebb",
        "on-background": "#1b1c1c",
        gold: "#FFD700",
      },
      fontFamily: {
        "display-lg": ["var(--font-vt323)", "monospace"],
        "headline-md": ["var(--font-vt323)", "monospace"],
        "headline-sm": ["var(--font-vt323)", "monospace"],
        "label-md": ["var(--font-vt323)", "monospace"],
        "label-sm": ["var(--font-vt323)", "monospace"],
        "body-lg": ["var(--font-roboto-mono)", "monospace"],
        "body-sm": ["var(--font-roboto-mono)", "monospace"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.2", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "1.2", fontWeight: "400" }],
        "label-md": ["18px", { lineHeight: "1.0", letterSpacing: "1px", fontWeight: "400" }],
        "label-sm": ["14px", { lineHeight: "1.0", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "1.4", fontWeight: "400" }],
      },
      spacing: {
        gutter: "16px",
      },
      maxWidth: {
        "container-max": "1120px",
      },
    },
  },
  plugins: [],
};

export default config;
